environment:

    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python27-x64"

build: off

install:
    # We need wheel installed to build wheels
    - "%PYTHON%\\python.exe -m pip install wheel twisted pypiwin32"
    - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

test_script:
    - "%PYTHON%\\python.exe run_tests.py"

after_test:
    - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
    - path: dist\*
